# yaml-language-server: $schema=https://schemas.brigade.sh/schemas-v2/project.json
apiVersion: brigade.sh/v2
kind: Project
metadata:
  id: docker-tools
description: Brigade's Docker Tools built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/docker-tools
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
    - release:published
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/docker-tools.git
